# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: CaribData
    url: caribdata/
    weight: 20
  - name: Features
    url: /#features
    weight: 30
  - name: Solutions
    url: /#solutions
    weight: 40
  - name: IDB
    url: idb/
    weight: 50
  - name: REDCap
    weight: 60
    hasChildren: true
  - parent: REDCap
    name: Get-Started
    url: get-started/
    weight: 61
  - parent: REDCap
    name: Citation
    url: citation/
    weight: 62
  - parent: REDCap
    name: Security
    url: security/
    weight: 63
  - name: Resources
    weight: 70
    hasChildren: true
  - parent: Resources
    name: Blog
    url: blog/
